# Generated by Django 3.0.8 on 2020-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='first name')),
                ('last_name', models.CharField(max_length=300, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('O', 'O')], max_length=5, null=True, verbose_name='blood type')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='height')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('blood_pressure', models.FloatField(blank=True, null=True, verbose_name='blood pressure')),
                ('allergies', models.CharField(blank=True, max_length=200, null=True, verbose_name='allergies')),
                ('medical_conditions', models.CharField(blank=True, max_length=300, null=True, verbose_name='medical conditions')),
                ('organ_date_registration', models.DateField(blank=True, null=True, verbose_name='organ date registration')),
                ('organs_to_be_donated', models.TextField(blank=True, null=True, verbose_name='organs to be donated')),
                ('is_accepted', models.BooleanField(blank=True, null=True, verbose_name='is accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='first name')),
                ('last_name', models.CharField(max_length=300, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
            },
        ),
    ]
